### ISSUE TITLE
0.3.2 checklist

### ISSUE THREAD

**Issue by teto** [teto/pymptcpanalyzer#21]
Objectives for release 0.3.2 (https://github.com/teto/mptcpanalyzer/milestone/2):
- [x] add/fix tests
- [x] provide tput/gput 
- [x] replace *Mapping  by dataclass instead of NamedTuple
- [x] add some methods to MptcpAnalyzerParser
- [x] fix the mypy error around is_loaded and with_argparser_test
- [x] fix legends/title when only one destination
- [x] add pandas/mptcpanalyzer version to the cache dependencies
- [x] use `__format__()` / f-string for some classes like TcpConnection. Or for plot title
- [x] pandas 0.25
- [x] don't recompute reinjections twice
- [x] Prevent lua scripts from interfering

**Comment by teto** [comment]
just waiting for pandas 0.25 since that solve some problems with the plots.

**Comment by teto** [comment]
released
