### ISSUE TITLE
Meta issue for 0.3.3

### ISSUE THREAD

**Issue by teto** [teto/pymptcpanalyzer#29]
https://github.com/teto/mptcpanalyzer/milestone/2
- [x] load time with the appropriate type 
- [ ] fix dss plot (https://github.com/matplotlib/matplotlib/pull/13788#issuecomment-528155351) fixed. Waiting for matplotlib 3.3.0 release
- [ ] autocomplete of stream with valid values (display of score too)
- [ ] bump to pandas > 1.0

**Comment by teto** [comment]
bestprefix ignored :( https://github.com/tbielawa/bitmath/issues/90
